name: Auto Merge

on:
    push:
        branches:
            - develop

jobs:
    merge:
        runs-on: ubuntu-latest

        steps:            
            - name: Checkout repository
              uses: actions/checkout@v2

            - name: Merge changes
              run: |
                    git config user.name "GitHub Actions"
                    git config user.email "srinivasan07051978@gmail.com"
                    git checkout main
                    git merge --no-ff --no-edit develop
                    git push origin main
